### ISSUE TITLE
QuantStamp Audit: QSP-5 Potential gas-cost issues in mode function

### ISSUE THREAD

**Issue by ongrid** [lidofinance/lido-dao#155]
[QuantStamp security assessment](https://github.com/lidofinance/lido-dao/files/5561204/QuantStampReport.pdf) of [v0.1.0-rc.1](https://github.com/lidofinance/lido-dao/releases/tag/v0.1.0-rc.1) raised the following security issue:

# Issue: QSP-5

| Short Descr. | Potential gas-cost issues in `mode` function |
|-------------|--------|
| Severity | Low Risk |
| Files affected | Algorithm.sol |

## Description

In `Algorithm.sol`, the documentation says “low gas cost” but the algorithm takes quadratic time in the worst case. Because this worst case is not triggered when most oracle members agree, the impact is unclear. However, one can leverage Solidity having strong cryptographic hashes as a primitive to implement a version of this algorithm where the role of dataValues and dataValuesCounts is fulfilled by a mapping. The running time would become linear.

## Recommendations

Consider revising the approach in `Algorithm.sol`

**Comment by ongrid** [comment]
@lxzrv could you please investigate possible approaches with mapping-based counter? Result: Jupyter notebook with solidity code, bytecodes, transactions and receipts. + gas consumption comparison. Repo: https://github.com/lidofinance/ad-hoc-experiments

**Comment by lxzrv** [comment]
It's hard to make it via jupyter notebook, so i have done it just adding new tests with gas measuring.

2 branches were compared:
1. [pre_mainnet_oracle_fixes](https://github.com/lidofinance/lido-dao/commit/e5af77c80eb661a76889663b44623cb1853ab0bc) (current algo)
2. [new_mode_calculation](https://github.com/lidofinance/lido-dao/commit/69cca2b09018d368be8018d5d2d93d659219251e) (new algo)

<table>
<tr>
<th> pre_mainnet_oracle_fixes </th>
<th> new_mode_calculation </th>
</tr>

<tr>
<td>
<pre>
    When oracles report same data
      1 members are reporting sequentially (quorum = 1:)
report 1 (quorum) : 117715
Total: 117715
        ✓  (110ms)
      2 members are reporting sequentially (quorum = 2:)
report 1 : 87343
report 2 (quorum) : 106214
Total: 193557
        ✓  (99ms)
      3 members are reporting sequentially (quorum = 3:)
report 1 : 87343
report 2 : 74269
report 3 (quorum) : 109712
Total: 271324
        ✓  (129ms)
      4 members are reporting sequentially (quorum = 4:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 (quorum) : 113210
Total: 351017
        ✓  (165ms)
      5 members are reporting sequentially (quorum = 5:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 (quorum) : 116708
Total: 432636
        ✓  (194ms)
      6 members are reporting sequentially (quorum = 6:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 : 80047
report 6 (quorum) : 120207
Total: 516182
        ✓  (223ms)
      7 members are reporting sequentially (quorum = 7:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 : 80047
report 6 : 81973
report 7 (quorum) : 123706
Total: 601654
        ✓  (239ms)
      8 members are reporting sequentially (quorum = 8:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 : 80047
report 6 : 81973
report 7 : 83899
report 8 (quorum) : 127204
Total: 689051
        ✓  (280ms)
      9 members are reporting sequentially (quorum = 9:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 : 80047
report 6 : 81973
report 7 : 83899
report 8 : 85825
report 9 (quorum) : 130703
Total: 778375
        ✓  (370ms)
      10 members are reporting sequentially (quorum = 10:)
report 1 : 87343
report 2 : 74269
report 3 : 76195
report 4 : 78121
report 5 : 80047
report 6 : 81973
report 7 : 83899
report 8 : 85825
report 9 : 87751
report 10 (quorum) : 134202
Total: 869625
        ✓  (332ms)
    When oracles report different data (quorum = 2)
      2 members are reporting sequentially:
report 1 : 87343
report 2 (quorum) : 106214
Total: 193557
        ✓  (58ms)
      3 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 (quorum) : 110335
Total: 298759
        ✓  (88ms)
      4 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 (quorum) : 114656
Total: 408248
        ✓  (119ms)
      5 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 (quorum) : 119177
Total: 522224
        ✓  (153ms)
      6 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 : 113943
report 6 (quorum) : 123899
Total: 640889
        ✓  (187ms)
      7 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 : 113943
report 6 : 118630
report 7 (quorum) : 128821
Total: 764441
        ✓  (230ms)
      8 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 : 113943
report 6 : 118630
report 7 : 123517
report 8 (quorum) : 133942
Total: 893079
        ✓  (275ms)
      9 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 : 113943
report 6 : 118630
report 7 : 123517
report 8 : 128604
report 9 (quorum) : 139264
Total: 1027005
        ✓  (309ms)
      10 members are reporting sequentially:
report 1 : 87343
report 2 : 101081
report 3 : 105168
report 4 : 109455
report 5 : 113943
report 6 : 118630
report 7 : 123517
report 8 : 128604
report 9 : 133892
report 10 (quorum) : 144786
Total: 1166419
        ✓  (344ms)
</pre>
</td>
<td>
<pre>
    When oracles report same data
      1 members are reporting sequentially (quorum = 1:)
report 1 (quorum) : 156356
Total: 156356
        ✓  (79ms)
      2 members are reporting sequentially (quorum = 2:)
report 1 : 128203
report 2 (quorum) : 106529
Total: 234732
        ✓  (99ms)
      3 members are reporting sequentially (quorum = 3:)
report 1 : 128203
report 2 : 78376
report 3 (quorum) : 108455
Total: 315034
        ✓  (114ms)
      4 members are reporting sequentially (quorum = 4:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 (quorum) : 110381
Total: 397262
        ✓  (160ms)
      5 members are reporting sequentially (quorum = 5:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 (quorum) : 112307
Total: 481416
        ✓  (174ms)
      6 members are reporting sequentially (quorum = 6:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 : 84154
report 6 (quorum) : 114233
Total: 567496
        ✓  (207ms)
      7 members are reporting sequentially (quorum = 7:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 : 84154
report 6 : 86080
report 7 (quorum) : 116159
Total: 655502
        ✓  (237ms)
      8 members are reporting sequentially (quorum = 8:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 : 84154
report 6 : 86080
report 7 : 88006
report 8 (quorum) : 118085
Total: 745434
        ✓  (258ms)
      9 members are reporting sequentially (quorum = 9:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 : 84154
report 6 : 86080
report 7 : 88006
report 8 : 89932
report 9 (quorum) : 120011
Total: 837292
        ✓  (384ms)
      10 members are reporting sequentially (quorum = 10:)
report 1 : 128203
report 2 : 78376
report 3 : 80302
report 4 : 82228
report 5 : 84154
report 6 : 86080
report 7 : 88006
report 8 : 89932
report 9 : 91858
report 10 (quorum) : 121937
Total: 931076
        ✓  (316ms)
    When oracles report different data (quorum = 2)
      2 members are reporting sequentially:
report 1 : 128203
report 2 (quorum) : 106529
Total: 234732
        ✓  (55ms)
      3 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 (quorum) : 113086
Total: 368782
        ✓  (88ms)
      4 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 (quorum) : 118107
Total: 506153
        ✓  (125ms)
      5 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 (quorum) : 123128
Total: 648381
        ✓  (166ms)
      6 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 : 142064
report 6 (quorum) : 128149
Total: 795466
        ✓  (191ms)
      7 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 : 142064
report 6 : 146921
report 7 (quorum) : 133170
Total: 947408
        ✓  (229ms)
      8 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 : 142064
report 6 : 146921
report 7 : 151779
report 8 (quorum) : 138191
Total: 1104208
        ✓  (268ms)
      9 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 : 142064
report 6 : 146921
report 7 : 151779
report 8 : 156636
report 9 (quorum) : 143213
Total: 1265866
        ✓  (298ms)
      10 members are reporting sequentially:
report 1 : 128203
report 2 : 127493
report 3 : 132350
report 4 : 137207
report 5 : 142064
report 6 : 146921
report 7 : 151779
report 8 : 156636
report 9 : 161493
report 10 (quorum) : 148234
Total: 1432380
        ✓  (346ms)
</pre>
</td>
</tr>

</table>

As we can see from comparsion, there is no any profit with using O(N) mode calculating algo because we need more storage writes (reportValues and reportValuesCount) in that case. Economy on final mode calculation due to solidity implementation nuances is too small to cover increased reportBeacon() method gasprice.
