### ISSUE TITLE
Use unstructured storage for conventional state vars in upgradable contracts

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#181]
The variables that currently don't use Unstructured Storage:

**Lido.sol:** `withdrawalCredentials` (will be added in #204: `shares`, `totalShares`).
**LidoOracle.sol:** `members`, `quorum`, `pool`, `beaconSpec`, `earliestReportableEpochId`, `lastReportedEpochId`, `gatheredEpochData`.
**NodeOperatorsRegistry.sol:** `operators`, `totalOperatorsCount`, `activeOperatorsCount`, `pool`.

**Comment by skozin** [comment]
Please postpone `_shares` and `_totalShares` until #204 is merged.

**Comment by skozin** [comment]
This is pretty hard to do in Solidity v0.4.x since its assembly language doesn't support setting locations that storage variables are pointed to, e.g. this won't work (yielding a `TypeError: Storage variables cannot be assigned to`):

```solidity
function _getNopMapping(bytes32 _storagePosition) internal view returns (mapping(address => uint256) storage result) {
    assembly {
        result_slot := _storagePosition
    }
}
```

If we used Solidity v0.6+, then even accessing mappings to reference types would be trivial: https://gist.github.com/skozin/344d9c7d2270cac0c3f9373c2f43c846.

In v0.4x, this can be done in a non-fragile way for mappings to value types (see https://gist.github.com/skozin/7c13e9ebcb513af56f98fc6cd533b5ef) and for arrays of value types (see https://gist.github.com/skozin/b3e1f38bb31387ce3b8d023ddb9f7e33).

Given the complexity of the implementation, I would suggest migrating to unstructured storage for all value-typed variables and skipping it for reference-typed variables (`_shares` in `Lido`, `members` and `gatheredEpochData` in `LidoOracle`, `operators` in `NodeOperatorsRegistry`).
