### ISSUE TITLE
StETH shares UX improvements

### ISSUE THREAD

**Issue by ujenjt** [lidofinance/lido-dao#210]
User deposits 1 eth (1*10^18 wei) and gets 0.99999...99 stETH in return. We want to give them exactly 1 stETH because of UX reasons. To bypass rounding errors we can do this for every user:
```
uint256 sharesAmount = token.getSharesByPooledEth(deposit+1); // provided depoist + 1 wei
```

Needs additional investigation that this does't breaks another things.

**Comment by ujenjt** [comment]
probably is better to inject this in StETH.balanceOf() -> tokens + 1 wei

**Comment by skozin** [comment]
> probably is better to inject this in StETH.balanceOf() -> tokens + 1 wei

Agree with this, since doing `uint256 sharesAmount = token.getSharesByPooledEth(deposit+1)` won't always yield the desired result due to shares rounding, and even if it does, minting additional shares might easily turn `1 ETH` back to `0.9(9) ETH` due to the same rounding reasons.

Another downside is that doing this for all submits will break the rule that the amount of StETH minted always equals the amount of ETH in control of the protocol.

On the other hand, doing `StETH.balanceOf() -> tokens + 1 wei` will reliably break the use-case of transferring all tokens belonging to an address. That said, this use-case is already broken due to the fact that the balances of all holders may change slightly due to rounding when someone submits ETH to the pool and new shares are minted as a result.
