### ISSUE TITLE
Tests for operator penalties / slashing cases

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#228]
We want to have automated test scenarios for cases where some Node Operators get penalties and/or slashed and subsequently stopped by the DAO.

**Comment by ongrid** [comment]
This is possible as one of the branches of hierarchically-organized tests I mentioned in #224 Need to decide should we proceed with this

**Comment by ongrid** [comment]
BTW Vlad Kuchinsky reported that he observes unexpected behavior of node operators reward addresses balances in the case of penalties. After the oracles report decreased numbers, the stETH balances of node operators reward addresses grow instead of decrease. I wasn't able to reproduce this within e2e. In my environment the behavior meets expectations.

```
### BEFORE REPORT
Now 10:05:53.327753
Current frame: [7560, 1607324733, 1607324892]
Total Pooled Ethers: 94.162715085888 
BufferedEther: 27.0
Nop0 Addr:0x27E9727FD9b8CdDdd0854F56712AD9DF647FaB74 stETH:0.6415011828062892
Nop1 Addr:0x9766D2e7FFde358AD0A40BB87c4B88D9FAC3F4dd stETH:1.2830023656125784
Epoch: 7560
depositedValidators: 3
beaconValidators: 3
beaconBalance: 67.162715085888
totalPooledEther: 94.162715085888

## AFTER REPORT with 10% decrease
Now 10:07:03.183769
Current frame: [7560, 1607324733, 1607324892]
Total Pooled Ethers: 87.4464435772992 
BufferedEther: 27.0
Nop0 Addr:0x27E9727FD9b8CdDdd0854F56712AD9DF647FaB74 stETH:0.5957453216580839
Nop1 Addr:0x9766D2e7FFde358AD0A40BB87c4B88D9FAC3F4dd stETH:1.1914906433161678
Epoch: 7560
depositedValidators: 3
beaconValidators: 3
beaconBalance: 60.4464435772992
totalPooledEther: 87.4464435772992
```

I guess it's either some sort of misconfiguration of Vlad's environment or some processes (like deposits or reporting increased numbers)  running in parallel.

**Comment by ongrid** [comment]
Had a troubleshooting session with Vlad. Not reproduced in his e2e env with incremental (step-by-step) approach.

BTW this business-logic should be extensively covered by tests.

**Comment by kadmil** [comment]
Added scenario tests in pulls #225, #236 and #256. Current scenario covers penalties and slashings (stopped validators / node operators) cases
