### ISSUE TITLE
Single getter for oracle daemons

### ISSUE THREAD

**Issue by ongrid** [lidofinance/lido-dao#230]
Currently the Oracle contract doesn't expose the following information that could improve the visibility

* last reported epoch See @vshvsh [comment](https://github.com/lidofinance/lido-oracle/pull/58#discussion_r537049706)
* info regarding non-current but not-voted-yet frames (currently the contract is responsible for all the decisions. Daemon calculates without additional checks and pre-plays the TX play in EVM locally. If it didn't revert, we send it on the wire and hope for the best.)
* info regarding members and their participation (currently we assume we didn't vote. If that assumption is incorrect we get negative results playing TX internally)

All the info relevant for Oracle Daemon can be combined into the single getter that will keep the algorithm more trivial (no need for iterations). 
Encoder: ABIv2
Breaking change: Yes
Model (preliminary):

```
In: oracle_confract.getOracleState()
Out:
{
lastReportedFrame: {'epochId' : 123, 'startTime': 1234567, 'endTime': 1234567, 'quorum': 2, 'reported': {'0xdeadBeef': false, '0xdeaddead': true ...}  }
reportableFrames: [{'epochId' : 234, 'startTime': 2234567, 'endTime': 2234567, 'quorum': 2, 'reported': {'0xdeadBeef': false, '0xdeaddead': true ...}  }, {'epochId' : 334, 'startTime': 3234567, 'endTime': 3234567, 'quorum': 2, 'reported': {'0xdeadBeef': false, '0xdeaddead': false ...}  }]
}
```

The getters to deprecate:

```
function getCurrentReportableEpochs()
        public view
        returns (
            uint256 firstReportableEpochId,
            uint256 lastReportableEpochId
        )

function getCurrentEpochId() public view returns (uint256)

function getCurrentFrame()
```

**Comment by ongrid** [comment]
* frame should contain `pushed` attribute (has it been pushed or not)
* frame should contain pushed values
* frame (or more generally - returned response) should contain quorum
* the frame should contain the set of members with bool attribute `reported` AND/OR individual reported values.

```
    struct Frame {
        uint256 epochId;
        uint256 startTime;
        uint256 endTime;
        uint256 quorum;
        Report pushed;
        Member members;
    }

    struct Member {
        address addr;
        bool reported;
        Report report;
    }
```

**Comment by lxzrv** [comment]
I tried to implement this feature using experimental ABIEncoderV2 but faced a problem that the new getters returns wrong RLP encoded data. I could not determine exactly what the error was, because another contract with same getters returns correct data. Tests that show this behaviour you can find [here](https://github.com/lidofinance/lido-dao/blob/f5ddbef812d8e04c48b5922ffccd61e09ab02b92/test/0.4.24/encoderV2.test.js).
For example,
```sol
oracle = new web3.eth.Contract(LidoOracle.abi, oracleProxyAddress)
txn_data = oracle.methods.testEncoderV2(1).encodeABI()
result = await web3.eth.call({ to: oracleProxyAddress, data: txn_data })
console.log(result)
```
returns this wrong hex string as answer:
```
0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000c0
```
This string can not be decoded with Js decoder. Simple (not web3 raw) call fails with reason
```
Error: insufficient data for uint256 type (arg="a", coderType="uint256", value="0x")
```
It's very interesting that contract with only these same getters works correctly in identical conditions (both of oracle and test contract are deployed and use delegateProxy. Initially, i thought that delegateProxy is the problem, but it isn't, checked in RemixIDE). Correct answer i got is:
```
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000
```
and it can be decoded to this:
```
[
  [
    '0',    '0',
    '0',    [],
    a: '0', b: '0',
    c: '0', d: []
  ]
]
```
