### ISSUE TITLE
LID-14 Insecure `BytesLib` dependency in `Lido.sol`

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#247]
The `BytesLib` version used in the current (`v0.2.1-rc.0`) implementation has a critical vulnerability in the `BytesLib.slice` method. The audit suggests ensuring Lido from passing any user-supplied input to the arguments of `BytesLib.slice`.

**Comment by skozin** [comment]
This is [not currently exploitable](https://github.com/GNSPS/solidity-bytes-utils#important-fixes-changelog) since we're not supplying user input to `BytesLib.slice`, but we'll need to update the dependency as soon as we update our codebase to a new Solidity version (the current one, `v0.4.x`, is not supported by the fixed dependency version).

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
